
export const CONSTELLATION_LINES = [
  { from: 'Betelgeuse', to: 'Alnitak' },
  { from: 'Alnitak', to: 'Alnilam' },
  { from: 'Alnilam', to: 'Mintaka' },
  { from: 'Mintaka', to: 'Rigel' },
  { from: 'Mintaka', to: 'Bellatrix' },
  { from: 'Alnitak', to: 'Saiph' },
  { from: 'Betelgeuse', to: 'Bellatrix' },
  { from: 'Rigel', to: 'Saiph' },
  { from: 'Dubhe', to: 'Merak' },
  { from: 'Merak', to: 'Phecda' },
  { from: 'Phecda', to: 'Megrez' },
  { from: 'Megrez', to: 'Alioth' },
  { from: 'Alioth', to: 'Mizar' },
  { from: 'Mizar', to: 'Alkaid' },
  { from: 'Megrez', to: 'Dubhe' },
  { from: 'Sirius', to: 'Adhara' },
  { from: 'Adhara', to: 'Wezen' },
  { from: 'Sirius', to: 'Mirzam' },
  { from: 'Castor', to: 'Pollux' },
  { from: 'Castor', to: 'Alhena' },
  { from: 'Pollux', to: 'Alhena' },
  { from: 'Acrux', to: 'Gacrux' },
  { from: 'Mimosa', to: 'Imai' },
  { from: 'Imai', to: 'Acrux' },
  { from: 'Gacrux', to: 'Mimosa' },
  { from: 'Rigil Kentaurus', to: 'Hadar' },
  { from: 'Regulus', to: 'Denebola' },
  { from: 'Schedar', to: 'Caph' },
  { from: 'Vega', to: 'Deneb' },
  { from: 'Deneb', to: 'Altair' },
  { from: 'Altair', to: 'Vega' }
];
